Charif Soheib abdelkader 

# FromZero

In [21]:
print("charif")

charif


In [1]:
x = 5


In [2]:
print(type(x))

<class 'int'>


In [6]:
x,y = 6,4

In [7]:
print(x)

6


In [8]:
print(y
     )

4


In [9]:
c = 2 + 4


In [10]:
print(c
     )

(2+4j)


In [11]:
%whos


Variable   Type       Data/Info
-------------------------------
c          complex    (2+4j)
x          int        6
y          int        4


In [12]:
%whos

Variable   Type       Data/Info
-------------------------------
c          complex    (2+4j)
x          int        6
y          int        4


In [13]:
del c 

In [14]:
%whos


Variable   Type    Data/Info
----------------------------
x          int     6
y          int     4


In [15]:
7//2

3

In [16]:
20//7

2

In [17]:
9//3


3

In [18]:
90//8

11

In [19]:
87//8

10

In [20]:
20%7

6

In [21]:
 3**3
    

27

In [22]:
e_2 = 50

In [23]:
print(e_2)

50


In [24]:
_ = 40


In [25]:
print(_)

40


In [26]:
%whos


Variable   Type    Data/Info
----------------------------
e_2        int     50
x          int     6
y          int     4


In [27]:
print(_)

40


In [28]:
%who

e_2	 x	 y	 


In [31]:
%whos

Variable   Type    Data/Info
----------------------------
y          int     4


In [30]:
del e_2,x

In [32]:
del all

NameError: name 'all' is not defined

In [33]:
7>8

False

In [34]:
3==3.2

False

In [35]:
3==3.0


True

In [36]:
print(round(5.88))

6


In [37]:
print(round(5.88,1))

5.9


In [38]:
divmod(9,3)

(3, 0)

In [39]:
divmod(22,7)

(3, 1)

In [49]:
print(isinstance((5,4),bool))


True


In [50]:
2**4


16

In [51]:
pow(2,4)

16

In [53]:
pow(2,4,7)

2

In [55]:
a = input("my age is : ")

my age is : 26 years old 


In [56]:
print(type(a))

<class 'str'>


In [57]:
%whos 

Variable   Type    Data/Info
----------------------------
a          str     26 years old 
y          int     4


In [1]:


print("hey")

hey


In [4]:
o = input('enter a number : ')
x = int(o)
while (x == 0):  
    
    x = input("give one different than zero")


print("nice one dude you typed " + x)

enter a number : 5


TypeError: can only concatenate str (not "int") to str

In [6]:
o = input('enter a number : ')
x = int(o)
while (x == 0):  
    
    x = int(input("give one different than zero"))


print("nice one dude you typed " + str(x))

enter a number : 0
give one different than zero00
give one different than zero4
nice one dude you typed 4


In [9]:
pow??
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [11]:

count = 1;
while (count<=3) :
    a = int(input("enter first value : "))
    b = int(input("enter seconde one : "))
    if a>b : 
        print(" la valeur de a  est plus grande que b et egal a " + str(a))
    elif b>a:
        print(" la valeur de b  est plus grande que a et egal a " + str(b))
    else : 
        print("ils sont egaux")
    h = 3-count

    print("you have " + str(3-count) + " other try") if h != 0 else  print("no more chance unfortunatly, Thank u for ur efforts")
         
    count = count +1
    
    

enter first value : 15
enter seconde one : 17
 la valeur de b  est plus grande que a et egal a 17
you have 2 other try
enter first value : 17
enter seconde one : 17
ils sont egaux
you have 1 other try
enter first value : 11
enter seconde one : 44
 la valeur de b  est plus grande que a et egal a 44
no more chance unfortunatly, Thank u for ur efforts


In [7]:
a = 18
b = 15 
print(b) if b>a else print(a) if a>b else print("egaux")

18


In [5]:
counti = 1
while (counti<3):
    u = int(input("put a number"))
    if u>=5 : 
        if u>20:
            print('this number is also above than 20 ')
        else: 
            print(" nice ")
    else : 
        print("the number is below 5")
        
    counti=counti+1

put a number7
 nice 
put a number8
 nice 


In [10]:
print(int(0//0
         ))

ZeroDivisionError: integer division or modulo by zero

In [13]:
count = 1
while (count<=3):
    x = float(input("enter a float"))
    y = int(round(x))

    if y<0:
        if y<x:
            intdialna = y+1
        else: 
            intdialna = y
    else : 
        if y>x:
            intdialna = y-1
        else: 
            intdialna = y
    count = count + 1         
    print(intdialna)
print("fin !" )

enter a float5.27
5
enter a float-4.22
-4
enter a float0.222
0
fin !


In [11]:
round(-4.9)

-5

In [4]:
i = int(input('enter a number : '))
print("cest le nombre " + str(i) +  " que vous avez mentionner")

enter a number : 47
cest le nombre 47 que vous avez mentionner


In [7]:
print("on vas afficher les nombres pair seulement")
count = 1

while count <= 10 : 
    if count%2 == 0:
        print(count)
    else: 
        pass
    count +=1

on vas afficher les nombres pair seulement
2
4
6
8
10


In [8]:

1%9

1

In [16]:
L = []
L.append(0)
L[0]=5
print(L)

[5]


In [5]:
L2 = []
for i in range (2,20,3):
    
    L2.append(i**2)
print(L2)
   

[4, 25, 64, 121, 196, 289]


In [6]:
S = {"charif",5,"fares"}
print(type(S))

<class 'set'>


In [11]:
D = {"A":5,"B":10}
for x in D : 
    print(x ,":", D[x])

A : 5
B : 10


In [15]:
x= 5 
print("charif " + str(x) +" aynek")

charif 5 aynek


In [1]:
%whos


Interactive namespace is empty.


In [2]:
a = 2

In [3]:
%whos

Variable   Type    Data/Info
----------------------------
a          int     2


In [159]:
L = [1,5,-3,7,6,9]

In [160]:
print(L1)

[1, 5, -3, 7, 6, 9]


In [161]:

for i in range (len(L)):
    min = L[i]
    indx = i
    count = i
    for j in range(i,len(L)):
        if L[j]<min:
            min = L[j]
            indx = count
            temp = L[i]
            L[i] = min
            L[j] = temp
        count = count +1
        print('le min dans ce cas est : ',min, " li kan f ", indx )
    

          L = [1,5,-3,7,6,9]
            
     
print(L)


le min dans ce cas est :  1  li kan f  0
le min dans ce cas est :  1  li kan f  0
le min dans ce cas est :  -3  li kan f  2
le min dans ce cas est :  -3  li kan f  2
le min dans ce cas est :  -3  li kan f  2
le min dans ce cas est :  -3  li kan f  2
le min dans ce cas est :  5  li kan f  1
le min dans ce cas est :  1  li kan f  2
le min dans ce cas est :  1  li kan f  2
le min dans ce cas est :  1  li kan f  2
le min dans ce cas est :  1  li kan f  2
le min dans ce cas est :  5  li kan f  2
le min dans ce cas est :  5  li kan f  2
le min dans ce cas est :  5  li kan f  2
le min dans ce cas est :  5  li kan f  2
le min dans ce cas est :  7  li kan f  3
le min dans ce cas est :  6  li kan f  4
le min dans ce cas est :  6  li kan f  4
le min dans ce cas est :  7  li kan f  4
le min dans ce cas est :  7  li kan f  4
le min dans ce cas est :  9  li kan f  5
[-3, 1, 5, 6, 7, 9]


In [60]:
print(len(L))

6


In [53]:
for k in range (6):
    print(k)

0
1
2
3
4
5


In [63]:
print(L)

[-3, -3, -3, -3, 1, 1]


In [162]:
def arreteMessage():
    print("done")
    print("move on dude ! ;)")
    

In [165]:
for i in range(5):
    print(i)
    arreteMessage()

0
1
2
3
4
done
move on dude ! ;)


In [4]:
%whos??


In [5]:
def printSuc():
    ''' This function print Suc tae li rabho bac'''
    
    print('bsahttkom les bacheliers')

In [11]:
divmod??

In [14]:
round??


In [31]:
def powListToNumber(i):
    count = 0
    for j in range (i+1) :
        u = j**2
        print("le carré de ",count," est ",u)
        
        count= count+1
    

In [32]:
powListToNumber(5)

le carré de  0  est  0
le carré de  1  est  1
le carré de  2  est  4
le carré de  3  est  9
le carré de  4  est  16
le carré de  5  est  25


In [ ]:
def printmsg(msg):
    while True:
        if isinstance(msg,str):
            print(msg)
            break
        else:
            print("please put a str format")
            printmsg(input())
            print
            
            

In [ ]:
printmsg(555)

In [39]:
isinstance?

In [1]:
pow??


In [12]:
def checkNumbers(a,b,c):
    if isinstance(a,(int,float)) and isinstance(b,(int,float)) and isinstance(c,(int,float)):
        
        print((a+b+c)**2)
    else:
        
        print('Error ! Please provide the right format of Numbers')
        
        for i in (a,b,c):
            
            if not isinstance(i,(int,float)):
                
                print(" we have type error : " , type(i))

In [13]:
checkNumbers(5,4,7)

256


In [14]:
checkNumbers(7,(4,5),'ggg')

Error ! Please provide the right format of Numbers
 we have type error :  <class 'tuple'>
 we have type error :  <class 'str'>


In [15]:
x = int(input())

50


In [16]:
def printoo(a,b,c):
    print("a egal a : ", a)
    print("a egal a : ", b)
    print("a egal a : ", c)

In [18]:
printoo(b=8,c=7,a='g')

a egal a :  g
a egal a :  8
a egal a :  7


In [20]:
printoo??

In [11]:
def multiadd(a,v):
        c = a*v+v
        return c


In [23]:
multiadd(v=int(input()),a=int(input()))

4
5
24


In [26]:

del u,k


try:
    u = int(input('enter the first number'))
except:
    u = int(input('please enter int or float number'))
try:
    k = int(input('enter the second number'))
except :
    try:
        k = int(input('please enter int or float number u have other chance'))
    except:
         print('smahlna nta mkwd')
    finally:
         print("roh kwd")

try: 
    m = multiadd(u,k)
    print(m/2)
except: 
    print("mankdrouch navancou a lkhra aewd ektbhom ghaya")
    u = int(input('enter the first number'))
    k = int(input('enter the second number'))
    m = multiadd(u,k)
    print("ur result is ", m/2)
finally: 
    print("alhamdoulleh li fhamt w rana kamlna")



enter the first number8
enter the second numberlol
please enter int or float number u have other chancell
smahlna nta mkwd
roh kwd
mankdrouch navancou a lkhra aewd ektbhom ghaya
enter the first number45
enter the second number41
ur result is  943.0
alhamdoulleh li fhamt w rana kamlna


In [19]:

%whos
del u

Variable   Type        Data/Info
--------------------------------
m          int         63
multiadd   function    <function multiadd at 0x000001F156F51A20>
r          int         63
u          int         8


In [27]:
print("hii")

hii


In [7]:
a = 8
b=5
def jdid(n,b):
    c= a*n*b
    return c
j = jdid(2,2)
print(j)
    

32


In [8]:
%whos

Variable   Type        Data/Info
--------------------------------
a          int         8
b          int         5
j          int         32
jdid       function    <function jdid at 0x00000228CBDCF2E0>


In [15]:
def kdim(y,u):
    j = y*a+u
    i= y*b+u
    return j,i


o,p = kdim(7,2)


In [16]:
%whos

Variable   Type        Data/Info
--------------------------------
a          int         8
b          int         5
j          int         32
jdid       function    <function jdid at 0x00000228CBDCF2E0>
kdim       function    <function kdim at 0x00000228CBDCE830>
o          int         58
p          int         37


In [30]:
def g():
    print("hello to the person who invoked g ")
    m = a+b
    
    print("mazalni")
    return m
     
    
    
g()

hello to the person who invoked g 
mazalni


13

In [29]:
g()

hello to the person who invoked g 


13

In [24]:
print(type(g()))

hello to the person who invoked g 
<class 'int'>


In [27]:
h = type(g())
print(h)

hello to the person who invoked g 
<class 'NoneType'>


In [56]:
def tyo(*args):
    sum =0
    for i in args:
        sum = sum+i
    return sum
    

In [60]:
tyo(5,4,38,222)


269

In [33]:
range()

TypeError: range expected at least 1 argument, got 0

In [34]:
range?


In [45]:
o = {"5" : 10,"4" : 8}

In [47]:
for i in o:
    print(i)

5
4


In [29]:
def varnameandposition(**args):
    summ = 0
    for i in args:
        
        print("we are on the position ",summ, " dont la clé est ",i," qui a la valeur ",args[i])
        summ+=1
    

In [31]:
varnameandposition(a=5, b="batata", c="yaheeew")

we are on the position  0  dont la clé est  a  qui a la valeur  5
we are on the position  1  dont la clé est  b  qui a la valeur  batata
we are on the position  2  dont la clé est  c  qui a la valeur  yaheeew


In [9]:
%whos

Variable             Type        Data/Info
------------------------------------------
varnameandposition   function    <function varnameandposit<...>on at 0x0000020509448EE0>


In [10]:
p = (5,5)

In [11]:
len(p)

2

In [27]:
d= (charif == 1,fares == 2)

NameError: name 'charif' is not defined

In [24]:
print(len(d))

2


In [25]:
print(d["fares"])

(5, 8)


In [32]:
q = 5
w=q
print(q,w)

5 5


In [33]:
w = 8
print(q,w)

5 8


In [34]:
L11 = [0,4,5]
L12 = L11

print(L11,L12
     )

[0, 4, 5] [0, 4, 5]


In [35]:
L12[0]= 8
print(L11,L12
     )

[8, 4, 5] [8, 4, 5]


In [59]:
def pardefo(z,m = 0 ):
    print(m,z)
    

In [61]:
pardefo(8)

0 8


In [42]:
pardefo(7)

7 5


In [43]:
pardefo(7,7)

7 7


In [52]:
def parfed(L=[]):
    for i in range(len(L)):
        c = L[i]**2
        L[i] = c
    print(L)


In [53]:
parfed()

[]


In [54]:
O=[8,7,5]
parfed(O)

[64, 49, 25]


In [82]:
def checkingargs(*args):
    count = 0
    for i in range(len(args)):
        if not(isinstance(args[i],(int,float))):
            count = count +1
            
        else: 
            pass
    if (count == len(args)):
        print('all ur variable are not int or float')
        return False
    elif (count ==0):
        
        return True
    
    else:
        print("one of ur value are not int or float")
        return False

In [83]:
checkingargs(5,"gg","gg")

one of ur value are not int or float


False

In [87]:
if (checkingargs("gg","rr","gg") == True ):
    print("rana ghaya")
else : 
    print("check the description above to know ")

all ur variable are not int or float
check the description above to know 


In [88]:
import sys
sys.path.append('C:/PythonFuc/')


In [100]:
from AllMyFunction import parfed2 as pp


In [101]:
pp()?

SyntaxError: invalid syntax (1586319889.py, line 1)

In [106]:
m = [5,5,5]
pp(m)


[25, 25, 25]


In [103]:
divmod??

In [95]:
parfed2??

Object `parfed2` not found.


In [96]:
AllMyFunction.pp??

Object `AllMyFunction.pp` not found.


In [107]:
print("hey")

hey


In [112]:
print("charif
soheib
abdelkader ")

SyntaxError: unterminated string literal (detected at line 1) (2793189350.py, line 1)

In [113]:
myName = "sohaib charif"
print(myName[-1])

f


In [114]:
len(myName)

13

In [121]:
print(myName[-1:-4])

In [130]:
def reverseText(s='ekteb kech haja w hna na9albouha yaw kima rak ta9ra'):
    x = ""
    for i in range(-1,-(len(s)+1),-1):
        x=x + s[i]
    print(x)
    

In [131]:
reverseText()

ar9at kar amik way ahuobla9an anh w ajah hcek betke


In [132]:
u = """ je m'appele charif soheib abdelkader
j'habite a zeralda
j'ai 25 ans 
chaummeur
"""

In [133]:
reversed?


In [134]:
reverseText(u)


ruemmuahc
 sna 52 ia'j
adlarez a etibah'j
redakledba biehos firahc eleppa'm ej 


In [175]:
ma = " charifo sohaibo"
len(ma)
def lastFiveLetters(s):
    z= " "
    x = " 1"
    y = s+x
    for i in range(-9,-1):
        z = z+y[i]
    
    print(z)


In [176]:
lastFiveLetters('charifo sohaibo')

 sohaibo 


In [177]:
print(ma)

 charifo sohaibo


In [180]:
print(ma[-7::2])

shio


In [181]:
len(ma[3:5])

2

## Chaine de caractere 


Aya

In [182]:
a = '    charif Soheib ABDELKADER    '

print(a)

    charif Soheib ABDELKADER    


In [183]:
b = a.strip()

In [184]:
print(b)

charif Soheib ABDELKADER


In [185]:
c= b.lower()

In [186]:
print(c)

charif soheib abdelkader


In [187]:
o = '      myNameis Soheib abdelkader   '

In [188]:
print(o)

      myNameis Soheib abdelkader   


In [193]:
p = o.strip().lower().replace("mynameis","Assmi")

In [194]:
print(p)

Assmi soheib abdelkader


In [195]:
L = [8,8,7]

In [199]:
print(L[::-1])

[7, 8, 8]


In [3]:
namooo = 'charif jj soheib jj abdelkader'
print(namooo[::-1])

redakledba jj biehos jj firahc


In [239]:
k = namooo.split()

In [240]:
print(k)

['charif', 'jj', 'soheib', 'jj', 'abdelkader']


In [228]:
a.split()?


SyntaxError: invalid syntax (2206770986.py, line 1)

In [237]:
a.split?

In [249]:
def donnenompropre(x):
    y = x.split()
    
    if (len(y)==2):
        m = y[0].lower().capitalize()+' ' + y[1].upper()
    else : 
        m= y[0].lower().capitalize()+' ' + y[1].lower().capitalize()+' ' + y[2].upper()
    return m

In [267]:
oob=donnenompropre('CHARIF SOHEIB ABDELKADER')

In [260]:
h = ' charifc '
p= 'c'

In [265]:
h.count(p)

2

In [268]:
i = input('right the that ur searching')
if (i in oob): 
    print('ur name existe')
else : 
    print("makach li yaerfek")

right the that ur searchingCharif
ur name existe


In [279]:
oo = 'charif charif charif charif'
x = oo.count("charif",5,20)

In [280]:
print(x)

2


In [3]:
x = "lala"
u = "lolololo"
if x in u :
    print('yes')

In [4]:
print("hello to everyone that told me \" HELLO \" how r ya ?")

hello to everyone that told me " HELLO " how r ya ?


In [6]:
print(r"c:\number\r")

c:\number\r


In [41]:
x= 5 
L = [5,4,8,'sohaib',7]
def calculsomme(j=[4,5]):
    p=0
    for i in j : 
        
        if isinstance(i,(float,int)):
            p= p +i
            
            
        else:
            pass
        k = p*100
            
    return k
        

In [42]:
%whos



Variable      Type        Data/Info
-----------------------------------
L             list        n=5
calculsomme   function    <function calculsomme at 0x000001AAC2BA7A30>
namooo        str         charif jj soheib jj abdelkader
o             int         2400
x             int         5


In [43]:
o = calculsomme()
print(o)

900


In [44]:
t1 = (7,5)
t2 = (8,10)
t3 = t1+t2
print(t3)

(7, 5, 8, 10)


In [48]:
print(t1[1])

5


In [52]:
L.copy?


In [49]:
del t1[1]

TypeError: 'tuple' object doesn't support item deletion

In [53]:
m1 = [5,5,8,9]
m2 = m1
m3 = m1.copy()
print(m1,m2,m3)

[5, 5, 8, 9] [5, 5, 8, 9] [5, 5, 8, 9]


In [54]:
m3[2]=9
print(m1,m2,m3)

[5, 5, 8, 9] [5, 5, 8, 9] [5, 5, 9, 9]


In [55]:
m2[2] = 0
print(m1,m2,m3)

[5, 5, 0, 9] [5, 5, 0, 9] [5, 5, 9, 9]


In [29]:
so= {'charif',"soheib",5,8,4}
so2 = so
so3 = so+so2

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [27]:
%whos

Variable   Type    Data/Info
----------------------------
dictio     dict    n=6
dictio2    dict    n=6


In [65]:
print("charif" in so)

True


In [87]:
print(so)

{'i', 'charifaaa', 'soheib', 5, 4, 'f', 8, 's', 'o', 'a', 'h', 'r', 'y', 'charifo', 'n', 'c', 'charif'}


In [67]:
so.add("charifo")

In [86]:
so.remove("yanis")


In [83]:
so.remove?

In [54]:
dictio = {"charif":"sohaib","allel":"fares", "Agesoheib":25}
print(dictio)

{'charif': 'sohaib', 'allel': 'fares', 'Agesoheib': 25}


In [11]:
dictio["ageFares"] = 30

In [8]:
print(dictio)

{'charif': 'sohaib abdelkader', 'allel': 'fares', 'Agesoheib': 25}


In [7]:
dictio["charif"] = "sohaib abdelkader"

In [9]:
dictio["amira"] = "kbira"

In [12]:
print(dictio)

{'charif': 'sohaib abdelkader', 'allel': 'fares', 'Agesoheib': 25, 'amira': 'kbira', 'ageFares': 30}


In [13]:
dictio2 = dictio

In [14]:
print(dictio,dictio2)

{'charif': 'sohaib abdelkader', 'allel': 'fares', 'Agesoheib': 25, 'amira': 'kbira', 'ageFares': 30} {'charif': 'sohaib abdelkader', 'allel': 'fares', 'Agesoheib': 25, 'amira': 'kbira', 'ageFares': 30}


In [15]:
dictio2["AgeAmira"] = 34

In [22]:
diction4=dictio+dictio2

TypeError: unsupported operand type(s) for +: 'dict' and 'dict'

In [20]:
type?

In [21]:
type(dictio)

dict

In [23]:
%whos

Variable   Type    Data/Info
----------------------------
dictio     dict    n=6
dictio2    dict    n=6


In [32]:
Lj=[7,8,9,7]
print(Lj)

[7, 8, 9, 7]


In [33]:
del Lj[0,1]
print(Lj)

TypeError: list indices must be integers or slices, not tuple

In [62]:
Listp = [5,4,8]
print(Listp)
del Listp[0]
print(Listp)

[5, 4, 8]
[4, 8]


In [53]:
LL= [5,4,7,'charif', 8,'charif','charif'] 
ind=0
count=0
Lo=[]
Lpp=[]
for y in LL:
    if y!="charif":
        Lpp.append(y)
        
        count = count+1
    else:
        ind = count
        Lo.append(ind)
        count = count+1
print(Lo)
print(Lpp)


LL = Lpp.copy()

print(LL)
     



[3, 5, 6]
[5, 4, 7, 8]
[5, 4, 7, 8]


In [33]:
print(len(Lo))

3


In [ ]:
print(LL
     )

In [2]:
L=1
%whos

Variable   Type    Data/Info
----------------------------
L          int     1


In [55]:
%whos

Variable   Type    Data/Info
----------------------------
L          int     1
LL         list    n=4
LLL        list    n=5
Lo         list    n=3
Lpp        list    n=4
count      int     7
dictio     dict    n=3
i          int     6
ind        int     6
p          int     6
y          str     charif
z          int     0


In [57]:
dictio2 = {"messaoudi" : "aicha","sahouli":"tahar"}

In [59]:
print(dictio,dictio2)

{'charif': 'sohaib', 'allel': 'fares', 'Agesoheib': 25} {'messaoudi': 'aicha', 'sahouli': 'tahar'}


In [60]:
dictio.update(dictio2)

In [61]:
dictio

{'charif': 'sohaib',
 'allel': 'fares',
 'Agesoheib': 25,
 'messaoudi': 'aicha',
 'sahouli': 'tahar'}

In [65]:
dictio["charif"]="aek"

In [66]:
dictio

{'charif': 'aek',
 'allel': 'fares',
 'Agesoheib': 25,
 'messaoudi': 'aicha',
 'sahouli': 'tahar'}

In [67]:
dictio["charifo"]="aek"

In [68]:
dictio

{'charif': 'aek',
 'allel': 'fares',
 'Agesoheib': 25,
 'messaoudi': 'aicha',
 'sahouli': 'tahar',
 'charifo': 'aek'}

In [70]:
LO = [8,'CHARIF',9,9,8,7,2]
print(LO)

[8, 'CHARIF', 9, 9, 8, 7, 2]


In [71]:
LO.remove("CHARIF")

In [72]:
print(LO)

[8, 9, 9, 8, 7, 2]


In [73]:
%whos

Variable   Type    Data/Info
----------------------------
L          int     1
LL         list    n=4
LLL        list    n=5
LO         list    n=6
Lo         list    n=3
Lpp        list    n=4
count      int     7
dictio     dict    n=6
dictio2    dict    n=2
i          int     6
ind        int     6
p          int     6
y          str     charif
z          int     0


In [75]:
help(LO.append)

Help on built-in function append:

append(object, /) method of builtins.list instance
    Append object to the end of the list.



In [79]:
print(LO)

[8, 9, 9, 8, 7, 2, [5, 7]]


In [80]:
LO.append(5,7)

TypeError: list.append() takes exactly one argument (2 given)

In [82]:
for i in dictio:
    print(i,dictio[i])

charif aek
allel fares
Agesoheib 25
messaoudi aicha
sahouli tahar
charifo aek


In [83]:
s={"sohaib",88888,41,'charif'}

In [84]:
for x in s:
    print(x)

88888
41
charif
sohaib


In [85]:
dictio

{'charif': 'aek',
 'allel': 'fares',
 'Agesoheib': 25,
 'messaoudi': 'aicha',
 'sahouli': 'tahar',
 'charifo': 'aek'}

In [86]:
print(dictio)

{'charif': 'aek', 'allel': 'fares', 'Agesoheib': 25, 'messaoudi': 'aicha', 'sahouli': 'tahar', 'charifo': 'aek'}


In [93]:
p = 9
x=9
k=18
print("x is grandé") if x>p else print("x is petit") if x<p else print("egaux p and x")

egaux p and x


In [97]:
[x+p for x in range(10)]


[9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [98]:
print(LL)

[5, 4, 7, 8]


In [127]:
L1= [5,4,7]
L2= [1,2,3]
L3 = L1 + L2
print(L3)

[5, 4, 7, 1, 2, 3]


In [126]:
L7 = {0,0,0}
p=0
for i in range(len(L2)):
    p = L1[i]+L2[i]
    L7.add(int(p))
    
print(L7)
    

{0, 10, 6}


In [116]:
print(L5)

{4, 5, 7}


In [6]:
def GetDataFromUser():
    Dxnr={}
    while True : 
        StudentID = input("put the student ID : ")
        
        

        if StudentID in Dxnr:
            print("This student ID Already Exist")
        else :
            marksList = input("Put the marks List separated with coma (,): ")
            
            Dxnr[StudentID] = marksList.split(",")
            moreStudent = input("Type no/yes to continue : ")
        if moreStudent.lower() == "no":
            return Dxnr

In [5]:
StudentDataa = GetDataFromUser()

put the student ID : 1445
Put the marks List separated with coma (,): 10,14,18,11
Type no if u finish : yes
put the student ID : 14478
Put the marks List separated with coma (,): 11,09,16,11
Type no if u finish : y
put the student ID : 1445
Put the marks List separated with coma (,): 11,11,11,11
Type no if u finish : no
This student ID Already Exist


In [6]:
print(StudentDataa)

{'1445': ['10', '14', '18', '11'], '14478': ['11', '09', '16', '11']}


In [7]:
d = {"charif" : "sohaib"}
print(d)

{'charif': 'sohaib'}


In [8]:
d["charif"]= "fares"

In [9]:
print(d)

{'charif': 'fares'}


In [3]:
def averageStudent(D={"54441":[4,4,7,8]}):
    DxnrAv={}
    for i in D:
        x=0
        for j in D[i]:
            x = x + int(j)
        DxnrAv[i]= x/len(D[i])
    return DxnrAv

averageStudent()
            

{'54441': 5.75}

In [7]:
Listo = GetDataFromUser()

put the student ID : 14
Put the marks List separated with coma (,): 5,4,9
Type no/yes to continue : y
put the student ID : 14
This student ID Already Exist
put the student ID : 14
This student ID Already Exist
put the student ID : 15
Put the marks List separated with coma (,): 17,12,11
Type no/yes to continue : no


In [9]:
print(Listo,averageStudent(Listo))

{'14': ['5', '4', '9'], '15': ['17', '12', '11']} {'14': 6.0, '15': 13.333333333333334}


In [12]:
you = averageStudent(Listo)
print(you)

{'14': 6.0, '15': 13.333333333333334}


In [11]:
for i in you:
    print("The student : ", i , "got the average : ",you[i])

The student :  14 got the average :  6.0
The student :  15 got the average :  13.333333333333334


In [2]:
import numpy as np

In [40]:
a = np.array([4,7,9])

In [33]:
np.array?

In [34]:
dtype(a)

NameError: name 'dtype' is not defined

In [43]:
a.dtype

dtype('int32')

In [4]:
a.ndim

NameError: name 'a' is not defined

In [47]:
a[0]

4

In [48]:
k = (8,7)
k[0]

8

In [90]:
b= np.array([[[1,2,3],[5,4,8]],[[88,29,38],[25,44,78]],[[88,29,38],[25,44,78]],[[88,29,38],[25,44,78]]])
b.ndim


3

In [91]:
b.size

24

In [63]:
b.shape

(4, 2, 3)

In [92]:
b.shape[0]

4

In [93]:
b.reshape(8,3)

array([[ 1,  2,  3],
       [ 5,  4,  8],
       [88, 29, 38],
       [25, 44, 78],
       [88, 29, 38],
       [25, 44, 78],
       [88, 29, 38],
       [25, 44, 78]])

In [28]:
b[1][1][1]

44

In [29]:
B.SIZE

NameError: name 'B' is not defined

In [49]:
b.size

8

In [47]:
b.bytes

AttributeError: 'numpy.ndarray' object has no attribute 'bytes'

In [48]:
b.nbytes

64

In [60]:
c = np.zeros((3,4))

In [61]:
print(b)
print(c)

[[list([1, 2, 3]) list([5, 4, 8])]
 [list([88, 29, 38]) list([25, 44, 78])]
 [list([88, 29, 38]) list([25, 44, 78])]
 [list([88, 29, 38]) list([25, 44, 78, 4])]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [317]:
xx = np.arange(101,150,5)

In [318]:
print(xx)

[101 106 111 116 121 126 131 136 141 146]


In [66]:
list?

In [67]:
o = list

In [68]:
print(o)

<class 'list'>


In [71]:
o = list(range(101))

In [72]:
print(o)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]


In [75]:
k = np.random.permutation(np.arange(101))
print(k)

[ 93  97  21  82  79  76  48  15  22  28  23  68  99  77  80  60  37  90
  83  55  38  36  71  95  94   6  64  89  84  75  78  47  57  24  13  86
  11  50  12  31  34   0  63   4  26  91  17  67   3  59  16  87 100  92
   8  66  52  46  85  72  25  41  69   2  10  44  18  39  45  62  51  33
  30  70  98  73  40   7  35  65   5  96  88  74  81  61   9  53   1  42
  54  49  58  14  32  56  19  27  29  20  43]


In [40]:
np.random.randint(53)

17

In [41]:
np.random.rand(10)

array([0.13941014, 0.82170793, 0.79267521, 0.63957428, 0.5344697 ,
       0.61595985, 0.79231607, 0.39458232, 0.63298343, 0.58181003])

In [20]:
p = np.array([5,5,5,5,5,5,5,8,4,4,4,4,])

In [25]:
l = p.reshape(2,2,3)

In [105]:
p = np.random.randn(10)
print(p)
print(p[::-1])

[-0.71200377  0.15679279 -1.19153163  1.73260189  0.2490438   0.47356276
  0.28334168  0.2522128   2.21657779 -0.54019004]
[-0.54019004  2.21657779  0.2522128   0.28334168  0.47356276  0.2490438
  1.73260189 -1.19153163  0.15679279 -0.71200377]


In [83]:
randn?

Object `randn` not found.


In [84]:
np.random.randn?

In [89]:
m = np.ones(10)
print(m)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [97]:
h = np.array([5,5,5,5,5])
print(h)
k = h[0:3]
print(k)
k[0] = 8
print(k)
print(h)

[5 5 5 5 5]
[5 5 5]
[8 5 5]
[8 5 5 5 5]


In [100]:
x = np.where()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [101]:
h.reverse

AttributeError: 'numpy.ndarray' object has no attribute 'reverse'

In [3]:
import numpy as np
np.indices?

In [20]:
o = np.array([6,4,8,10,11,244,1557,1557,1445])

In [21]:
l = np.where(o == 1557)
print(l)
o[l]= 100

print(o)

(array([6, 7], dtype=int64),)
[   6    4    8   10   11  244  100  100 1445]


In [109]:
m = (o==10)

In [110]:
print(m)

[False False False  True False False False False]


In [15]:
o==10

array([False, False, False,  True, False, False, False, False])

In [16]:
for in o:

SyntaxError: invalid syntax (282166910.py, line 1)

In [59]:
oo = np.array([6,4,8,10,11,11,11,11,11,244,1557,1557,11,111445])

In [74]:
def FoundIndex(L,x,y):
    index = 0
    i=0
    Lindex = []
    for j in range(len(L)):

        if ((L[j] == x) or L[j] == y ):
            index = j
            Lindex.append(index)


        else: 
            j=j+1


    if len(Lindex)<1: 
        return print("element not found")
    else:
       
            
        return print("your elements is located in : ", Lindex)

In [75]:
FoundIndex(oo,11,1557)

your elements is located in :  [4, 5, 6, 7, 8, 10, 11, 12]


In [68]:
np.where(o == 24774)

(array([], dtype=int64),)

In [136]:
b= np.array([[[88,88,3],[0,4,8]],[[88,29,38],[25,44,78]],[[88,29,38],[25,44,78]],[[11,29,99],[25,44,99]]])

In [144]:
v = np.argwhere(b == 99)

In [148]:
print(b.ndim)
print(b.size)
print(int(v.size/2))
print(v)


3
24
3
[[3 0 2]
 [3 1 2]]


In [82]:
b.ndim

3

In [149]:
b.shape

(4, 2, 3)

In [106]:
m = np.arange(101)

In [107]:
print(m)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [112]:
m = np.random.permutation(m)

In [113]:
print(m)

[ 93  70  18  63  30  87  49  56   1  71  14  13  55  29  37  82  69  52
  99  85   5  64  16  28  98  66  77  20  35  27  10   9  89  51  31  94
  33  92  26 100   6  68  46  11  59  61  44   3  91   4  86  62  22  97
  17  47   0   8  15  12  32  40  78  83  80  88  39  23   7  57  95  96
  58  79  76  73  24  25  42  54  75   2  81  38  90  50  84  19  34  41
  36  67  48  45  21  53  74  60  72  43  65]


In [115]:
q = np.arange(201)(np.random.permutation(q))

NameError: name 'q' is not defined

In [93]:
wrandon = np.rint(10*(np.random.rand(4,4))).astype(int)

In [94]:
print(wrandon)

[[8 0 2 4]
 [8 1 6 8]
 [8 7 6 7]
 [5 8 1 6]]


In [95]:
print(wrandon[1])

[8 1 6 8]


TypeError: only size-1 arrays can be converted to Python scalars

In [96]:
print(wrandon[::-1,0])
print(wrandon.T)

[5 8 8 8]
[[8 8 8 5]
 [0 1 7 8]
 [2 6 6 1]
 [4 8 7 6]]


In [226]:
wrandon

array([[1, 6, 0, 6],
       [6, 2, 7, 4],
       [8, 3, 4, 9],
       [9, 6, 1, 3]])

In [229]:
wrandon.T

array([[1, 6, 8, 9],
       [6, 2, 3, 6],
       [0, 7, 4, 1],
       [6, 4, 9, 3]])

In [230]:
wrandon.T*wrandon

array([[ 1, 36,  0, 54],
       [36,  4, 21, 24],
       [ 0, 21, 16,  9],
       [54, 24,  9,  9]])

In [232]:
print(wrandon*wrandon.T)

[[ 1 36  0 54]
 [36  4 21 24]
 [ 0 21 16  9]
 [54 24  9  9]]


In [234]:
  import numpy.linalg as alg

In [237]:
e = np.random.rand(3,3)
print(e)

[[0.31593296 0.75524899 0.97286021]
 [0.95156473 0.42222884 0.36163739]
 [0.91631875 0.70301365 0.77099641]]


In [244]:
k = alg.inv(e)
print(k)

[[ -10.36034954  -14.76872364   20.00021559]
 [  58.45283225   94.13804614 -117.91270395]
 [ -40.98560752  -68.28497785   85.04276632]]


In [249]:
k.sort(axis=0)

In [250]:
print(k)

[[-117.91270395  -40.98560752   20.00021559]
 [ -68.28497785  -10.36034954   85.04276632]
 [ -14.76872364   58.45283225   94.13804614]]


In [270]:
li = np.array(np.random.randint(50,size=(3,2)))
li.ndim

2

In [288]:

li[1,1]=23
li[2,0]=23
print(li)

[[ 4 27]
 [23 23]
 [23 35]]


In [289]:
li[li<40]
print(li[1,1])

23


In [294]:
print()

[[2 1]]


In [311]:
c = np.argwhere(li==80)
li[c] = 40

In [312]:
print(li)

[[40 40]
 [40 40]
 [39 38]]


In [319]:
vv = np.random.randint(30,size=(3,4))
print(vv)

[[13 28 14 29]
 [ 9  3 16 14]
 [21 10 26 11]]


In [322]:
ll = vv[2,1:]

In [323]:
print(ll)

[10 26 11]


In [354]:
ll2 = vv[[False,False,True],[False,True,True,True]]

In [353]:
print(ll2)

[10 26 11]


In [338]:
ll3 = np.array([1,5,4,8])
ll4 = ll3[[True,False,False,True]]

In [339]:
print(ll4)

[1 8]


In [355]:
ll2[len(ll2)-1] = 111111
print(ll2)

[    10     26 111111]


In [356]:
print(vv)

[[13 28 14 29]
 [ 9  3 16 14]
 [21 10 26 11]]


In [357]:
ll[len(ll)-1] = 1222222

In [358]:
print(vv)

[[     13      28      14      29]
 [      9       3      16      14]
 [     21      10      26 1222222]]


In [359]:
ow = np.random.randint(4,size=(4,2,3,3))

In [360]:
ow

array([[[[2, 2, 1],
         [0, 1, 2],
         [1, 2, 1]],

        [[0, 1, 3],
         [1, 0, 1],
         [2, 0, 2]]],


       [[[0, 2, 1],
         [0, 3, 0],
         [0, 2, 2]],

        [[3, 2, 0],
         [0, 1, 3],
         [3, 2, 3]]],


       [[[1, 1, 3],
         [2, 2, 0],
         [0, 1, 0]],

        [[3, 3, 3],
         [1, 1, 1],
         [2, 1, 3]]],


       [[[1, 0, 1],
         [0, 0, 0],
         [1, 3, 1]],

        [[3, 1, 0],
         [0, 0, 2],
         [3, 2, 2]]]])

In [3]:
import numpy as np
kk = np.arange(101)


In [362]:
kk

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [380]:
b = kk[3:6]

In [381]:
b

array([3, 4, 5])

In [386]:
b2 = kk[3:6]

In [387]:
b2

array([3, 4, 5])

In [399]:
b2[0]= 8
print(kk)

[ 99  99  99   8  99  99  99  99  99  99  99  99  99  99  99  99  99  99
  99  99  99  99  99  99  99  99  99  99  99  99  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [5]:
mmm = kk[(kk<30)  (kk<50)] 

In [6]:
print(mmm)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [391]:
u[0:] = 99

In [395]:
kk

array([ 99,  99,  99,  99,  99,  99,  99,  99,  99,  99,  99,  99,  99,
        99,  99,  99,  99,  99,  99,  99,  99,  99,  99,  99,  99,  99,
        99,  99,  99,  99,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
bored = np.random.randint(10,size=(3,4))
print(bored)

[[5 5 6 1]
 [4 8 4 6]
 [3 6 6 8]]


In [27]:
bored2 = np.array([[1,2],[2,2],[3,2]])

In [28]:
print(bored2)

[[1 2]
 [2 2]
 [3 2]]


In [29]:
print(bored + bored2)

ValueError: operands could not be broadcast together with shapes (3,4) (3,2) 

In [33]:
print(np.sort(bored,axis=1))

[[1 5 5 6]
 [4 4 6 8]
 [3 6 6 8]]


In [31]:
np.sort?

In [39]:
print(np.vstack((bored,bored2)))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [42]:
bored.shape

(3, 4)

In [51]:
randomarr = np.arange(2,5,1).reshape(3,1)
print(randomarr)

[[2]
 [3]
 [4]]


In [44]:
np.arange?

In [52]:
print(bored,randomarr)

[[5 5 6 1]
 [4 8 4 6]
 [3 6 6 8]] [[2]
 [3]
 [4]]


In [53]:
print(bored)
print(randomarr)

[[5 5 6 1]
 [4 8 4 6]
 [3 6 6 8]]
[[2]
 [3]
 [4]]


In [56]:
print(np.vstack((bored,np.random.permutation(randomarr))))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 1

In [82]:
j =np.random.permutation(np.arange(10))
print()

In [83]:
print(j)
print(np.sort(j))
p = np.flip(np.sort(j))

print(p)

[8 0 6 1 2 5 3 7 9 4]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


In [66]:
rj = 

In [67]:
print(rj)

[9 8 7 6 5 4 3 2 1 0]


In [87]:
np.random.rand(4)

array([0.82627613, 0.42273739, 0.81800304, 0.98900917])

In [104]:
LO = np.random.rand(1000)

In [106]:
%timeit np.sum(LO)
%timeit sum(LO)


11.2 µs ± 262 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
188 µs ± 2.99 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


45

In [107]:
import pandas as pd

In [108]:
pd.__version__

'1.5.3'

In [124]:
ponda = pd.Series([5,4,7,8],index=[25,"b","c","d"])
print(ponda)

25    5
b     4
c     7
d     8
dtype: int64


In [114]:
ponda.values

array([5, 4, 7, 8], dtype=int64)

In [115]:
type(ponda.values)

numpy.ndarray

In [116]:
type(ponda)

pandas.core.series.Series

In [117]:
ponda.index

Index([25, 'b', 'c', 'd'], dtype='object')

In [128]:
dictii = {"charif":"soheib","allel":"fares"}
dictipandas = pd.Series(dictii)
print(type(dictii))
print(type(dictipandas))

<class 'dict'>
<class 'pandas.core.series.Series'>


In [120]:
dictipandas.index

Index(['charif'], dtype='object')

In [125]:
dictipandas['charif']

'soheib'

In [130]:
dictii["charif":"allel"]


TypeError: unhashable type: 'slice'

In [131]:
dictipandas["charif":"allel"]

charif    soheib
allel      fares
dtype: object

In [384]:
nom = pd.Series([10,20,30,40],index=[1,2,3,4])

dc1 = {1:"Messaoud",2:"charif",3:'Charif',4:"Charif"}
dc2 = {1:'Aicha',2:"Aicha",3:'samira',5:"yamina"}

prnom =  pd.Series([1,2,3,4],index=["Messaoudi","charif","Charif","Charif"])

nomm = pd.Series(["Aicha","zicha","samira","yamina"],index=[1,4,3,5])
Listo = pd.DataFrame({"La Note":nom,"Prénom":nomm, "Nom":prnom})

C:\Users\My PC\AppData\Local\Temp\ipykernel_5688\2233096955.py:9: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  Listo = pd.DataFrame({"La Note":nom,"Prénom":nomm, "Nom":prnom})


ValueError: cannot reindex on an axis with duplicate labels

In [392]:


nomm.loc[1:4]

1    Aicha
4    zicha
dtype: object

In [364]:
prnom1 =  pd.Series(dc1)

nomm1 = pd.Series(dc2)
Listo2 = pd.DataFrame([nom,nomm1,prnom1])
Listo2

1       2       3       4       5
0      10.0    20.0    30.0    40.0     NaN
1     Aicha   Aicha  samira     NaN  yamina
2  Messaoud  charif  Charif  Charif     NaN

In [357]:
oo= Listo2.T
oo.dropna()

0       1         2
1  10.0   Aicha  Messaoud
2  20.0   Aicha    charif
3  30.0  samira    Charif

In [371]:
Listo

La Note  Prénom        Nom
1     10.0   Aicha  Messaoudi
2     20.0   Aicha     charif
3     30.0  samira     Charif
4     40.0     NaN     Charif
5      NaN  yamina        NaN

In [408]:
Listo.loc[2:4,"La Note":"Nom"]

La Note  Prénom     Nom
2     20.0   Aicha  charif
3     30.0  samira  Charif
4     40.0     NaN  Charif

In [349]:
Listo2

1     2       3       4      9       8
0      10.0  20.0    30.0    40.0    NaN     NaN
1     Aicha   NaN  samira  yamina  Aicha     NaN
2  Messaoud   NaN  Charif  Charif    NaN  charif

In [343]:
Listo2.dropna()

Empty DataFrame
Columns: [1, 2, 3, 4, 9, 8]
Index: []

In [306]:
(Listo.values[np.argwhere(Listo.values == "Messaoudi")])

array([[[10.0, 'Aicha', 'Messaoudi'],
        [30.0, 'samira', 'Charif']]], dtype=object)

In [307]:
np.argwhere(Listo.values == "Messaoudi")

array([[0, 2]], dtype=int64)

In [308]:
Listo.values[0,1]

'Aicha'

In [309]:
Listo

La Note  Prénom        Nom
1     10.0   Aicha  Messaoudi
2     20.0     NaN        NaN
3     30.0  samira     Charif
4     40.0  yamina     Charif
8      NaN     NaN     charif
9      NaN   Aicha        NaN

In [310]:
Listo["Scaled"] =Listo["La Note"]/5

In [311]:
Listo

La Note  Prénom        Nom  Scaled
1     10.0   Aicha  Messaoudi     2.0
2     20.0     NaN        NaN     4.0
3     30.0  samira     Charif     6.0
4     40.0  yamina     Charif     8.0
8      NaN     NaN     charif     NaN
9      NaN   Aicha        NaN     NaN

In [312]:
del Listo['Scaled']

In [313]:
Listo

La Note  Prénom        Nom
1     10.0   Aicha  Messaoudi
2     20.0     NaN        NaN
3     30.0  samira     Charif
4     40.0  yamina     Charif
8      NaN     NaN     charif
9      NaN   Aicha        NaN

In [314]:
Listo['La Note']

1    10.0
2    20.0
3    30.0
4    40.0
8     NaN
9     NaN
Name: La Note, dtype: float64

In [315]:
o = "messaoudi"
p =Listo[Listo['Nom']==o.capitalize()]
Listo[Listo['Nom']==o.capitalize()]

La Note Prénom        Nom
1     10.0  Aicha  Messaoudi

In [316]:
u = 'CHARIF'
print(u.lower())

charif


In [317]:
k= len(p["Nom"])

In [318]:
type(k)

int

In [319]:
Listo

La Note  Prénom        Nom
1     10.0   Aicha  Messaoudi
2     20.0     NaN        NaN
3     30.0  samira     Charif
4     40.0  yamina     Charif
8      NaN     NaN     charif
9      NaN   Aicha        NaN

In [320]:
Listo.fillna("NO NAME")

La Note   Prénom        Nom
1     10.0    Aicha  Messaoudi
2     20.0  NO NAME    NO NAME
3     30.0   samira     Charif
4     40.0   yamina     Charif
8  NO NAME  NO NAME     charif
9  NO NAME    Aicha    NO NAME

In [ ]:
ho = pd.DataFrame("")

In [323]:
%whos

Variable      Type         Data/Info
------------------------------------
LO            ndarray      1000: 1000 elems, type `float64`, 8000 bytes
Listo         DataFrame       La Note  Prénom       <...>   NaN   Aicha        NaN
bored         ndarray      3x4: 12 elems, type `int32`, 48 bytes
bored2        ndarray      3x2: 6 elems, type `int32`, 24 bytes
dictii        dict         n=2
dictipandas   Series       charif    soheib\nallel      fares\ndtype: object
j             ndarray      10: 10 elems, type `int32`, 40 bytes
k             int          1
kk            ndarray      101: 101 elems, type `int32`, 404 bytes
lll           ndarray      4: 4 elems, type `float64`, 32 bytes
mmm           ndarray      50: 50 elems, type `int32`, 200 bytes
nom           Series       1    10\n2    20\n3    30\n4    40\ndtype: int64
nomm          Series       1     Aicha\n9     Aicha\<...>    yamina\ndtype: object
np            module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
o  

In [410]:
L = [5,5,5,5,5,5]
L222 = L["True","False","False","False","False","False"]

TypeError: list indices must be integers or slices, not tuple

In [415]:
k = input("donnez un entier svp :" )

try: 
    print("la multiplacation fois 4 de votre numero est : ", int(k)*4)
except:
    print("yek gotlek med entier laa !!!")

donnez un entier svp :5
la multiplacation fois 4 de votre numero est :  20


In [3]:
cher = "Charif soheib Charif abdelkader"
cher.count("Charif")

2

In [4]:
cher.replace("Charif","Messaoudi")

'Messaoudi soheib Messaoudi abdelkader'

In [9]:
x = input('give ur first value ')
y = input("give ur second value ")



try:
    f = int(x)+int(y)
    print(" la somme des deux egal a : ",f)
except Exception as e:
    print("Srat error li hiya : ",e)
    print("La somme egal a : None")

give ur first value 78
give ur second value 788
 la somme des deux egal a :  866
